# fly.toml app configuration file generated for rough-darkness-8435 on 2023-09-27T15:12:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-darkness-8435"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
